#!/bin/bash
#
# Regenerate the vendor makefiles from proprietary-files.txt.
# APKs cannot use PRODUCT_COPY_FILES, so they become prebuilt modules.
#
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/../../../vendor/mudita/kompakt"
LIST="$HERE/proprietary-files.txt"
mkdir -p "$OUT"

# ---------------------------------------------------------------- plain files
{
    echo "# Blobs from the stock vendor partition, copied verbatim."
    echo "# Generated by setup-makefiles.sh; do not edit."
    echo ""
    echo "PRODUCT_SOONG_NAMESPACES += vendor/mudita/kompakt"
    echo ""
    echo "PRODUCT_PACKAGES += \\"
    grep "^vendor/.*\.apk$" "$LIST" | while read -r f; do
        echo "    $(basename "$f" .apk) \\"
    done
    echo ""
    echo "PRODUCT_COPY_FILES += \\"
    grep "^vendor/" "$LIST" | grep -v "\.apk$" | sed \
        "s|^vendor/\(.*\)$|    vendor/mudita/kompakt/proprietary/vendor/\1:\$(TARGET_COPY_OUT_VENDOR)/\1 \\\\|"
} > "$OUT/kompakt-vendor.mk"

python3 - "$OUT/kompakt-vendor.mk" <<"PY"
import sys, re
p = sys.argv[1]
out = []
for block in open(p).read().split("\n\n"):
    b = block.rstrip()
    if b.endswith("\\"):
        b = b[:-1].rstrip()
    out.append(b)
open(p, "w").write("\n\n".join(out) + "\n")
PY

# ---------------------------------------------------------------------- apks
{
    echo "# Prebuilt APKs from the stock vendor partition."
    echo "# Generated by setup-makefiles.sh; do not edit."
    echo ""
    echo "LOCAL_PATH := \$(call my-dir)"
    echo ""
    grep "^vendor/.*\.apk$" "$LIST" | while read -r f; do
        name=$(basename "$f" .apk)
        echo "include \$(CLEAR_VARS)"
        echo "LOCAL_MODULE := $name"
        echo "LOCAL_MODULE_OWNER := mudita"
        echo "LOCAL_SRC_FILES := proprietary/$f"
        echo "LOCAL_CERTIFICATE := PRESIGNED"
        echo "LOCAL_MODULE_PATH := \$(TARGET_OUT_VENDOR)/$(dirname "${f#vendor/}")"
        echo "LOCAL_MODULE_CLASS := APPS"
        echo "LOCAL_MODULE_SUFFIX := .apk"
        echo "LOCAL_DEX_PREOPT := false"
        echo "LOCAL_VENDOR_MODULE := true"
        echo "include \$(BUILD_PREBUILT)"
        echo ""
    done
} > "$OUT/Android.mk"

echo "wrote $OUT/kompakt-vendor.mk and $OUT/Android.mk"
